IMAGE_INSTALL += "openscap \
                  scap-security-guide \
                  pam-plugin-pwhistory \
                  pam-plugin-timestamp \
                  pam-passwdqc \
                  audispd-plugins \
                  libcap-bin \
                  libuser \
                  samhain \
                  strongswan \
                  openssh-misc \
                  sssd \
                  "
